# RUSS: 043 Reactor Room Digital Exhibit Spring 2020 JosÃ© Vergara

title: The Reactor Room
email: digitalscholarship@brynmawr.edu
description: >-
  An Immersive Chornobyl Installation
baseurl: "/reactor-room"
url: "https://digitalscholarship.brynmawr.edu"
search                   : true
search_full_content      : true

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jemoji

# Exclude from processing.
exclude:
  - .DS_Store
  - .sass-cache/
  - .jekyll-cache/
  - .vscode
  - .bundle
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package*
  - vendor
  - README.md
  - process.py
  - banner.js

encoding: "utf-8"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

collections:
  projects:
    output: true
    permalink: /projects/:path/

# Defaults
defaults:
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      header:
        overlay_filter: "rgba(50,50,50,.5)"
      author_profile: false
      read_time: false
      comments: # true
      share: false
      related: false
      btn_class: 'btn--inverse'

# DC Metadata defaults
dc:
  language: en
  relation_ispartof: 'swarthmore.edu'
